### ISSUE TITLE
Невозможно подключиться к серверу (проблема с EAC)

### ISSUE THREAD

**Issue by VladTop46** [Kaidoz/Rust-NoSteam#10]
При попытке подключиться к серверу с NoSteam невозможно подключиться:
Disconnected: EAC: Anti-cheat client protection not active (NullClient)

Сервер запускается с отключенным EAC, и без NoSteam без проблем можно подключиться.
Строка запуска:
./RustDedicated -batchmode -server.port 28015 -server.worldsize 4500 -server.seed 213846 +server.security "0" +server.secure "0" +server.eac 0 +server.encryption "0"

Буду рад любой помощи!

**Comment by Kaidoz** [comment]
Эти параметры запуска необходимо убрать и попробовать еще раз запуститься: +server.security "0" +server.secure "0" +server.eac 0 +server.encryption "0"
