### ISSUE TITLE
ошибка авторизации стим

### ISSUE THREAD

**Issue by zimerfmm** [Kaidoz/Rust-NoSteam#4]
здравствуйте. пытаюсь благодаря вашему плагину авторизоваться с пиратки на локальный сервер, дабы поиграть с другом, у которого лицензия. версия 1.0.5.0. в этоге при подключении выдает ошибку стим, в консоли отображается, что я был кикнут. не моги бы пожалуйста помочь? думаю, в таком случае логи будут бесполезны

**Comment by zimerfmm** [comment]
127.0.0.1:53225/76561199056806735/Zimerfm has auth level 2
127.0.0.1:53225/76561199056806735/Zimerfm Rejecting connection - Steam Auth Failed
Checking for new Steam Item Definitions.. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

**Comment by zimerfmm** [comment]
при том замечу, что на сервере я не менял assembly-csharp и айди игры стоит оригинальный

**Comment by zimerfmm** [comment]
![image](https://user-images.githubusercontent.com/68759988/170833776-1d45f3ae-e35e-4a44-9182-3f190227a4e1.png)

**Comment by Kaidoz** [comment]
dll установлена в папку Managed? Ошибка такая в целом не должна выходить. Стоит посмотреть логи и удостовериться, что плагин заработал. Если вы имеете ОС Windows, то установить версию для этой системы и соответственно тоже самое с Linux.

**Comment by zimerfmm** [comment]
dll установлено в managed, переносил cs скрипты, которые в архиве в oxide - plugins, так же и удалял, в любом случае одна и та же ошибка. Вы уверены, что ошибки не может быть со стороны плагина? сервер стартую с локального хостинга, платформа - windows.

**Comment by zimerfmm** [comment]
![image](https://user-images.githubusercontent.com/68759988/171832650-d9ce7c44-6912-437f-ba1a-9173ee6a5d93.png)
так и так не работает, итоговые выходные данные - выше. почти уверен, что сделал все правильно, а именно перекинул плагин по пути "rustds\RustDedicated_Data\Managed", а так же кинул плагины в папку с плагинами. вы проверяли плагин с пиратского клиента? возможно, я просто что-то не так сделал.

**Comment by Kaidoz** [comment]
Судя по красной ошибке плагин вовсе не работает/установлен.

**Comment by strekalovdenis** [comment]
у меня та же проблема что и у zimerfmm плагин NoSteam версии 2.5.0 установлен в "rust_dedicated\RustDedicated_Data\Managed" еще пытается включится rust+ щас еще закреплю файл с логом (я незнаю но возможно просто плагин не поддерживает новую версию сервера или я сделал что то не так)
![2024-12-21_11-49-00](https://github.com/user-attachments/assets/ddcc3fb8-6fe2-4aeb-840f-47d6879964fc)
