### ISSUE TITLE
Интеграция с Carbon

### ISSUE THREAD

**Issue by Artem936c** [Kaidoz/Rust-NoSteam#6]
Если у кого то адаптированый плагин для carbon?
Пытался сам, но ничего не вышло.

**Comment by Artem936c** [comment]
carbon это аналог oxide, только более удобный carbonmod.gg/

**Comment by Artem936c** [comment]
То есть я могу просто поменять AppId на 480, и никакого плагина не нужно будет? И с пиратки зайти и лицензии одновременно, так я полагаю?

**Comment by Kaidoz** [comment]
> carbon это аналог oxide, только более удобный carbonmod.gg/

ожидайте обновлений в ближайшее время. а так carbon по моему должен поддерживать обычные oxide-плагины

**Comment by Artem936c** [comment]
Понял, спасибо! Да, он поддерживает обычные oxide плагины, но для расширений, нужно поправить немного код, что у меня и не вышло)
[Carbon.Ext.Discord.zip](https://github.com/Kaidoz/Rust-NoSteam/files/11438947/Carbon.Ext.Discord.zip)

**Comment by Kaidoz** [comment]
Убрана зависимость от oxide, соответственно работает в Carbon.
